### ISSUE TITLE
Blocking my speedometer hud

### ISSUE THREAD

**Issue by RxBer** [AsepctDEVS/Aspect-Anticheat#1]
Today I installed this anticheat which I am very happy with, but I have two problems. Problem one is the following thing: The anticheat is blocking the speedometer from my server. When it's on I can't see the speedometer and when it's off I can see it.

The second problem is wheb I spanw a random vehicle what isn't a blackilsted vehicle I am getting banned for using god mode. (the same thing for blacklisted vehicles by the way)

with kind regards,
RxBer

**Comment by AsepctDEVS** [comment]
I am not sure if you have a clip of this going on it would help :) - Aspect

**Comment by RxBer** [comment]
https://youtu.be/UH3aZwM_4Mk this is the video.

**Comment by AsepctDEVS** [comment]
That's weird. Send me your config.Lua file without webhooks

**Comment by RxBer** [comment]
https://srcb.in/WS0lonV6t4
That's the config.lua. I only turned off god mode and antiVDM because I already have an antiVDM and on god mode already banned it if you took a car.

**Comment by AsepctDEVS** [comment]
Try starting the anticheat then in ur console restarting your hud

**Comment by RxBer** [comment]
Thank you that is working! But when i jump a few times in a row I get banned too. is there a fix for this or should i just set super jump to false?
https://streamable.com/u648u3

**Comment by RxBer** [comment]
I did! Thank you very much for helping meI appreciate it ❤️

**Comment by AsepctDEVS** [comment]
Closed. If you need any more support message me.
